"""Initial migration

Revision ID: a5655929ef5e
Revises: 9af6d2e05653
Create Date: 2026-09-02 11:55:47.269085

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a5655929ef5e'
down_revision: Union[str, None] = '9af6d2e05653'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
	"""Upgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.alter_column(
		'events',
		'created_at',
		existing_type=mysql.DATETIME(),
		server_default=sa.text('now()'),
		existing_nullable=False,
	)
	op.alter_column(
		'events',
		'updated_at',
		existing_type=mysql.DATETIME(),
		server_default=sa.text('now()'),
		existing_nullable=False,
	)
	op.alter_column(
		'tags',
		'created_at',
		existing_type=mysql.DATETIME(),
		server_default=sa.text('now()'),
		existing_nullable=False,
	)
	op.alter_column(
		'tags',
		'updated_at',
		existing_type=mysql.DATETIME(),
		server_default=sa.text('now()'),
		existing_nullable=False,
	)
	# ### end Alembic commands ###


def downgrade() -> None:
	"""Downgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.alter_column(
		'tags',
		'updated_at',
		existing_type=mysql.DATETIME(),
		server_default=sa.text('current_timestamp()'),
		existing_nullable=False,
	)
	op.alter_column(
		'tags',
		'created_at',
		existing_type=mysql.DATETIME(),
		server_default=sa.text('current_timestamp()'),
		existing_nullable=False,
	)
	op.alter_column(
		'events',
		'updated_at',
		existing_type=mysql.DATETIME(),
		server_default=sa.text('current_timestamp()'),
		existing_nullable=False,
	)
	op.alter_column(
		'events',
		'created_at',
		existing_type=mysql.DATETIME(),
		server_default=sa.text('current_timestamp()'),
		existing_nullable=False,
	)
	# ### end Alembic commands ###
